sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: 


  wechat:
    appid: 
    secret: 
    # 微信支付相关配置
    mchid: 
    mchSerialNo: 
    privateKeyFilePath: 
    apiV3Key: 
    weChatPayCertFilePath: 
    notifyUrl:  
    refundNotifyUrl:  

  #百度地图配置
  shop:
    address: 
  baidu:
    ak:
